name: Master Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew cleanCache clean build_them_all --refresh-dependencies

      - name: Show debug info
        run: ./gradlew --version

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-${{ steps.vars.outputs.sha_short }}
          prerelease: false
          name: Master Build ${{ github.sha }}
          files: |
            dist/*.jar